table Statuses
	lineageTag: 2b786d72-8888-46e2-80f3-b6557aa2a842

	column Status
		dataType: string
		lineageTag: dd31502d-c587-4444-a883-ba9cb6045b95
		summarizeBy: none
		sourceColumn: Status

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: ebefb519-de01-4dec-8c80-b595a9f7eeef
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = User

	partition Statuses = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8i9KSS1KTVHSUTJUitWJVgrOyCwoAPONwHzn/NKiTKgKY7CIS2pOZhlUxASqJrcgJ7UELGKqFBsLAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Status = _t, Index = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Status", type text}, {"Index", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

